package DataModel;

import DateUtil.DateFormatting;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;

@DynamoDBTable(tableName="ActivityLogs")
public class ActivityLog {

	private String ID;

	private LocalDateTime creationDate;

	private String logTypeByEntity;

	/**
	 * Invite/Remove/Add/Delete Participant or Item, finish shopping event, etc
	 *
	 */
	private LocalDateTime action;

	@DynamoDBHashKey(attributeName="ID")
	@DynamoDBAutoGeneratedKey
	public String getID() {
		return ID;
	}

	public void setID(String ID) {
		this.ID = ID;
	}

	@DynamoDBAttribute(attributeName="CreationDate")
	public String getCreationDate() {
		return DateFormatting.getFormattedDate(creationDate);
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = DateFormatting.setToFormattedDate(creationDate);
	}

	@DynamoDBAttribute(attributeName="TypeByEntity")
	public String getLogTypeByEntity() {
		return logTypeByEntity;
	}

	public void setLogTypeByEntity(String logTypeByEntity) {
		this.logTypeByEntity = logTypeByEntity;
	}

	@DynamoDBAttribute(attributeName="Action")
	public String getAction() {
		return DateFormatting.getFormattedDate(action);
	}

	public void setAction(String action) {
		this.action = DateFormatting.setToFormattedDate(action);
	}

	public ActivityLog(String logTypeByEntity, LocalDateTime action) {
		this.creationDate = LocalDateTime.now();;
		this.logTypeByEntity = logTypeByEntity;
		this.action = action;
	}

	public ActivityLog(){creationDate = LocalDateTime.now();}
}
