package DataModel;

import DateUtil.DateFormatting;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName="ShoppingLists")
public class ShoppingList{


	private String ID;

	private String shopperId;

	private LocalDateTime endedAt;

	private LocalDateTime creationDate;

	private String name;

	private String storeId;

	private boolean isActive;

	private List<String> participantIds;

	@DynamoDBHashKey(attributeName="ID")
	@DynamoDBAutoGeneratedKey
	public String getID() {
		return ID;
	}

	@DynamoDBAttribute(attributeName="ParticipantIds")
	public List<String> getParticipantIds() {
		return participantIds;
	}

	@DynamoDBAttribute(attributeName="ShopperId")
	public String getShopperId() {
		return shopperId;
	}

	@DynamoDBAttribute(attributeName="EndedAt")
	public String getEndedAt() {
		return DateFormatting.getFormattedDate(endedAt);
	}


	@DynamoDBAttribute(attributeName="CreationDate")
	public String getCreationDate() {
		return DateFormatting.getFormattedDate(creationDate);
	}

	@DynamoDBAttribute(attributeName="Name")
	public String getName() {
		return name;
	}

	@DynamoDBAttribute(attributeName="StoreId")
	public String getStoreId() {
		return storeId;
	}

	@DynamoDBAttribute(attributeName="IsActive")
	public boolean isActive() {
		return isActive;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setActive(boolean active) {
		this.isActive = active;
	}

	public void setID(String id) {
		this.ID = id;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = DateFormatting.setToFormattedDate(creationDate);
	}

	public void setParticipantIds(List<String> participantIds) {
		this.participantIds = participantIds;
	}


	public void setShopperId(String shopperId) {
		this.shopperId = shopperId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}
	public void setEndedAt(String endedAt) {
		this.endedAt = DateFormatting.setToFormattedDate(endedAt);
	}

	public ShoppingList(String shopperId,  String name, boolean isActive, List<String> participantId,String storeId) {
		this.shopperId = shopperId;
		this.name = name;
		this.isActive = isActive;
		this.participantIds = participantId;
		this.creationDate = LocalDateTime.now();
		this.storeId =storeId;
		this.setEndedAt("");
	}

	public ShoppingList()
	{
		this.creationDate = LocalDateTime.now();
	}
}
